#define MEDIA_CONVERTER_POWER_CONTROL_PIN D5
#define ROUTER_POWER_CONTROL_PIN D6
#define LIGHT_POWER_CONTROL_PIN D4
#define BATTERY_ANALOG_PIN A0
#define POWER_SENSE_PIN D2

#define WIFI_SSID_AP "SmartUPS"
#define WIFI_PASS_AP "12091209"

#define WIFI_SSID_STA "ENERGY"
#define WIFI_PASS_STA "v1502j2107"

#define MIN_BATTERY_VOLTAGE 2.5
#define MAX_BATTERY_VOLTAGE 4.2
